### ISSUE TITLE
Only show KC for a single boss

### ISSUE THREAD

**Issue by SuperNerdEric** [DenchyRS/better-godwars-overlay#1]
I am currently doing Nex and I only care about Ancient KC. It would be nice if there was an option to only see the KC for a single god type. 

You could either have it only show if you have more than 0 KC or have a checkbox for each individual boss you want to show. Once again this would be purely optional.

**Comment by DenchyRS** [comment]
Feature added in the latest update, It should be available soon pending the runelite teams approval :)

Thanks for the suggestion, please let me know if you find issues regarding it once it is available 👍
